public without sharing class CallyzerLeadWrapper 
{
        public String firstName;
        public String lastName;
        public String xnumber;
        public String assignmentStrategy;
        public String secondaryNumber ;
        public String devices ;
        public String deviceTags;
        public String status ;
        public String email;
        public String companyName;
        public String address1;
        public String address2;
        public String city;
        public String state;
        public String country;
        public String zip;
        public String source;
        public String description;
        public String leadTags;
        public String leadOption;
        public String assignToOption;
        public String tagOption;
       
 
}