public without sharing class DN_ServiceConstants {
    public static final string HASH_FUNCTION_ALOGORITHM		= System.label.Hash_Function_Algorithm;
    public static final string ENCRYPTION_ALOGORITHM		= System.label.Encryption_Algorithm;
    public static final String AVENUE_SUCCESS_URL           = System.label.AVENUE_SUCCESS_URL;
    public static final String AVENUE_CANCEL_URL            = System.label.AVENUE_CANCEL_URL;
}