global class ResponseWrapper {
    global class UserRecord {
        public String firstName;
        public String email;
        public String userId;
        public String phone;
        public UserAttributes attributes;
    }
    
    global class UserAttributes {
        public String Course;
        public String Id;
        // public String lead_status;
        public String Alternate_Phone;
        public String Alternate_Email;
        public String lead_id;
        public String Branch;
        public String CID;
        public String City;
        public String Country;
        public String Created_Date;
        public String Current_Domain;
        public String Designation;
        public String Email;
        public String Enquired_Course;
        public String LID;
        public String Lead_Gen_Path;
        public String Lead_Owner;
        public String Lead_Source;
        public String Lead_Status;
        public String Medium;
        public String Next_follow_up_datetime;
        public String Oppurtunity_Name;
        public String Oppurtunity_Owner;
        public String Organisation;
        public String Page_URL;
        public String Qualification;
        public String Reason_for_Dead;
        public String Stage;
        public String State;
        public String Vertical;
        public String Whatsapp_Opt_in;
        public String Years_of_Experience;
        public String leadstatus;
    }
}